

export const Users = [
    {
      id:1,
      profilePicture: "assets/persons/1.jpg",
      username: "Balram Kurmi",
    },
    {
      id:2,
      profilePicture: "assets/persons/2.jpg",
      username: "Abhishek silawat",
    },
    {
      id:3,
      profilePicture: "assets/persons/3.jpg",
      username: "Bhaskar rai",
    },
    {
      id:4,
      profilePicture: "assets/persons/4.jpg",
      username: "Anurag Yadav",
    },
    {
      id:5,
      profilePicture: "assets/persons/5.jpg",
      username: "Shivaji rai",
    },
    {
      id:6,
      profilePicture: "assets/persons/1.jpg",
      username: "Nikita Raikwar",
    },
    {
      id:7,
      profilePicture: "assets/persons/2.jpg",
      username: "Shivani Patel",
    },
    {
      id:8,
      profilePicture: "assets/persons/3.jpg",
      username: "Ayush Patel",
    },
    {
      id:9,
      profilePicture: "assets/persons/4.jpg",
      username: "Vardan Gour",
    },
    {
      id:10,
      profilePicture: "assets/persons/5.jpg",
      username: "Antesh Gour",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "assets/persons/posts/1.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "assets/persons/posts/2.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "assets/persons/posts/3.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "assets/persons/posts/4.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "assets/persons/posts/5.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "assets/persons/posts/1.jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "assets/persons/posts/2.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "assets/persons/posts/3.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "assets/persons/posts/4.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "assets/persons/posts/5.jpg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];